name: enzpred
channels:
- defaults
- conda-forge
- anaconda
- pytorch
- jamespreed
dependencies:
- brotlipy=0.7.0
- statsmodels=0.12.2
- rdkit
- yapf=0.29.0
- seaborn=0.10.1
- mkl_fft=1.0.15
- conda-minify=0.1.2
- pathos=0.2.7
- optuna=1.5.0
- pixman=0.38.0
- torchvision=0.5.0
- ipykernel=5.3.4
- mkl_random=1.1.1
- python-levenshtein=0.12.0
- cython=0.29.20
- pysocks=1.7.1
- pytz=2020.1
- pyqt=5.9.2
- scikit-learn=0.22.1
- pip:
    - tape-proteins==0.4
    - fair-esm
    - git+https://github.com/samgoldman97/protein-sequence-embedding-iclr2019
